# Generated by Django 4.0.4 on 2022-05-17 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('date_birth', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('biography', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(default='profile_pictures/default.png', max_length=255, upload_to='profile_pictures')),
                ('is_private', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('A', 'Admin'), ('S', 'Standard')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_from_set', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Follow',
            },
        ),
    ]
