# Generated by Django 4.0.4 on 2022-05-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('A', 'Admin'), ('S', 'Standard')], default='S', max_length=1),
        ),
    ]
