# Generated by Django 4.0.4 on 2022-05-17 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Hashtag',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_author_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Post',
            },
        ),
        migrations.CreateModel(
            name='PostHashtag',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('hashtag_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.hashtag')),
                ('post_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
            options={
                'db_table': 'PostHashtag',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CO', 'Comment'), ('LI', 'Like'), ('FO', 'Follower')], max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user_author_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Notification',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('post_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('user_author_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Like',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(max_length=255, upload_to='posts')),
                ('post_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='post.post')),
            ],
            options={
                'db_table': 'Image',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('post_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('user_author_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Favorite',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('post_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('user_author_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
    ]
